### ISSUE TITLE
Latest commit doesn't work on emacs 24

### ISSUE THREAD

**Issue by articuluxe** [IvanMalison/multi-line#3]
When trying to run multi-line using HEAD on emacs 24.5.1, I receive the following error:

`Symbol's value as variable is void: multi-line-respace`

There are other compile errors as well.

**Comment by colonelpanic8** [comment]
Thanks. Looking in to it. Everything seems to be working in Emacs 25.

**Comment by colonelpanic8** [comment]
@danrharms Thanks again for the issue, I had no idea things weren't working in emacs24. This should be fixed in d8775312a9e1044c21d340baa546256b8994014d. I set up a cask build that passes for this commit (https://travis-ci.org/IvanMalison/multi-line/builds/155476362) thatjust makes sure that everything compiles/requires in both emacs24 and emacs25 for now, but I plan to add tests soon. Hopefully things will not break like that again.

Please reopen this issue if you still see an issue, or comment if everything is better. Thanks again.

**Comment by articuluxe** [comment]
Yes, it works for me now. Thanks for looking into it.
